# Generated by Django 4.2.1 on 2023-09-15 13:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Studios',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('studio_name', models.CharField(blank=True, max_length=50)),
                ('studio_number_street', models.CharField(blank=True, max_length=5)),
                ('studio_street', models.CharField(blank=True, max_length=70)),
                ('studio_city', models.CharField(blank=True, max_length=50)),
                ('studio_post_code', models.CharField(blank=True, max_length=5)),
                ('studio_country', models.CharField(blank=True, max_length=30)),
                ('studio_state', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TattooStyle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('style_name', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True, max_length=1000)),
            ],
        ),
    ]
