# Generated by Django 4.2.1 on 2023-09-15 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_artist', '0002_rename_studios_userartist_studio'),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Studios',
            new_name='Studio',
        ),
    ]
