# Generated by Django 4.2.1 on 2023-09-15 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_rename_studios_studio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studio',
            name='studio_state',
        ),
        migrations.AddField(
            model_name='studio',
            name='opening_hours',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='studio',
            name='studio_address_complement',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='studio',
            name='studio_department',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='studio',
            name='studio_region',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='studio',
            name='studio_siret',
            field=models.CharField(blank=True, max_length=18),
        ),
        migrations.AlterField(
            model_name='studio',
            name='studio_city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='studio',
            name='studio_country',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='studio',
            name='studio_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='studio',
            name='studio_street',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
