# Generated by Django 4.2.1 on 2023-10-06 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_remove_studio_studio_state_studio_opening_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studio',
            name='studio_website',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='studio',
            name='opening_hours',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='studio',
            name='studio_country',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
