# Generated by Django 4.2.1 on 2023-09-15 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_artist', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userartist',
            old_name='studios',
            new_name='studio',
        ),
    ]
