# Generated by Django 4.2.1 on 2023-09-15 15:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import user_artist.utils
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user_artist', '0002_rename_studios_userartist_studio'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserArtistFlash',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to=user_artist.utils.user_flash_directory_path)),
            ],
        ),
        migrations.AddField(
            model_name='userartist',
            name='actif',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userartist',
            name='facebook',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='userartist',
            name='instagram',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='userartist',
            name='status',
            field=models.CharField(blank=True, max_length=75),
        ),
        migrations.AddField(
            model_name='userartist',
            name='x',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='userartistalbum',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=user_artist.utils.user_album_directory_path),
        ),
        migrations.DeleteModel(
            name='UserArtistDrawing',
        ),
        migrations.AddField(
            model_name='userartistflash',
            name='user_artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
