# Generated by Django 4.2.1 on 2023-10-06 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_artist', '0003_userartistflash_userartist_actif_userartist_facebook_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userartist',
            name='biography',
            field=models.TextField(blank=True, max_length=2500),
        ),
    ]
